name: Charter Dashboard CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup test data
        run: |
          mkdir -p data
          cp data/test_calendar_data.json data/calendar_data.json
      - name: Create package.json
        run: |
          echo '{"name":"charter-calendar-dashboard","version":"1.0.0","scripts":{"test":"jest"},"jest":{"testEnvironment":"jsdom","moduleFileExtensions":["js","json"],"testMatch":["**/tests/**/*.test.js"]},"devDependencies":{"jest":"^29.0.0","jest-environment-jsdom":"^29.0.0","node-fetch":"^2.6.1"}}' > package.json      - name: Validate JSON
        run: |
          jq . data/calendar_data.json
          
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup test data
        run: |
          mkdir -p data
          cp data/test_calendar_data.json data/calendar_data.json
      - name: Create package.json
        run: |
          echo '{"name":"charter-calendar-dashboard","version":"1.0.0","scripts":{"test":"jest"},"jest":{"testEnvironment":"jsdom","moduleFileExtensions":["js","json"],"testMatch":["**/tests/**/*.test.js"]},"devDependencies":{"jest":"^29.0.0","jest-environment-jsdom":"^29.0.0"}}' > package.json
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test